#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Reports single cell RNA-seq (scRNA-seq) reads mapping statistics.
It processes the BAM file generated by the Cell Ranger workflow.
"""

import argparse
import logging
import sys

from rseqc import scbam

__contributor__ = "Liguo Wang"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", action="version", version="5.0.2")
    parser.add_argument(
        "-i",
        "--infile",
        dest="bam_file",
        help="Input file in BAM foramt. Must have BAM alignment tags indicated below. ",
    )
    parser.add_argument(
        "--cb-tag",
        dest="CB_tag",
        default="CB",
        help="BAM alignment tag. Used to indicate error-corrected cellular barcode. default='%(default)s'",
    )
    parser.add_argument(
        "--re-tag",
        dest="RE_tag",
        default="RE",
        help="BAM alignment tag. Used to indicate the region type of the alignment (E = exonic, N = intronic, I = intergenic). default='%(default)s'",
    )
    parser.add_argument(
        "--tx-tag",
        dest="TX_tag",
        default="TX",
        help="BAM alignment tag. Used to indicate reads aligned to the same strand as the annotated transcripts. default='%(default)s'",
    )
    parser.add_argument(
        "--an-tag",
        dest="AN_tag",
        default="AN",
        help="BAM alignment tag. Used to indicate reads aligned to the antisense strand of the annotated transcripts. default='%(default)s'",
    )
    parser.add_argument(
        "--umi-tag",
        dest="UMI_tag",
        default="UB",
        help="BAM alignment tag. Used to indicat the error-corrected UMI. default='%(default)s'",
    )
    parser.add_argument(
        "--xf-tag",
        dest="xf_tag",
        default="xf",
        help="BAM alignment tag. Used to indicate reads confidently mapped to the feature. default='%(default)s'",
    )
    parser.add_argument(
        "--chrM-id",
        dest="mit_contig_name",
        default="chrM",
        help="The name of mitochondrial chromosome in BAM file. default='%(default)s'",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        dest="debug",
        default=False,
        help="Logical to determine if detailed running information is printed to screen.",
    )

    args = parser.parse_args()
    if args.debug:
        logging.basicConfig(
            format="%(asctime)s [%(levelname)s]  %(message)s", datefmt="%Y-%m-%d %I:%M:%S", level=logging.DEBUG
        )
    else:
        logging.basicConfig(
            format="%(asctime)s [%(levelname)s]  %(message)s", datefmt="%Y-%m-%d %I:%M:%S", level=logging.INFO
        )

    for file in [args.bam_file]:
        if not (file):
            parser.print_help()
            sys.exit(0)
        if not (file + ".bai"):
            logging.error("Cannot find the BAM index file.")
            sys.exit(0)

    scbam.mapping_stat(
        infile=args.bam_file,
        CB_tag=args.CB_tag,
        UMI_tag=args.UMI_tag,
        xf_tag=args.xf_tag,
        RE_tag=args.RE_tag,
        TX_tag=args.TX_tag,
        AN_tag=args.AN_tag,
        chrM_id=args.mit_contig_name,
    )
    logging.info("Done.")


if __name__ == "__main__":
    main()
